language: python

python:
    - "pypy"
    - "2.7"
    - "2.6"

install: python setup.py develop

script: python setup.py nosetests

notifications:
    irc:
        channels:
            - "ircs://irc.megworld.co.uk:9000#inboxen"
        use_notice: true

sudo: false
