language: python
dist: xenial

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - pypy2.7-6.0
    - pypy3.5-6.0

matrix:
  include:
    - python: "3.6"
      env: TOX_ENV=docs
      install: pip install tox
      script: tox -e $TOX_ENV
    - python: "3.6"
      env: TOX_ENV=lint,isort
      install: pip install tox
      script: tox -e $TOX_ENV

install: travis_retry pip install -q codecov tox

script: tox -e py  # run tox for the current version of Python

after_success: codecov

notifications:
    irc:
        channels:
            - "ircs://irc.megworld.co.uk:9000#inboxen"
        use_notice: true

sudo: false
